development:
#tier3
  host: 10.80.69.79
#macbook pro  
  #host: 10.139.235.137
  adapter: postgresql
  encoding: unicode
  database: musicbrainz_db
  pool: 5
  username: musicbrainz
  password: musicbrainz